### ISSUE TITLE
do not commit distribution files into git

### ISSUE THREAD

**Issue by anarcat** [rfrail3/tuptime#11]
hi!

this is pretty cool software! i see there is a debian package in the `deb-package` directory - where does it come from? How is it generated?

Normally, you commit only the `debian/` directory into source control, and  the `.deb` is distributed seperately. You could, for example, ship them with your [regular github releases](https://help.github.com/articles/creating-releases/). Obviously, the `.deb` should also be shipped with Debian itself, which would widen the distribution of this software significantly! There is a RFP (Request For Package) in the Debian BTS (Bug Tracking System) here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=638422

I would even go as far as recommending you start with a new repository, to remove all those binary files from the history. Right now, about 80% of the size of the repository is the `.git` history, which is huge - normally, it should closer to 50% for small shell scripts like this...

**Comment by rfrail3** [comment]
Hi Anacrat,

The .deb package located inside deb-package directory is the result of the deb-files directory that exists into the pkf-files branch. There, the howto.txt have two commands that are executed over deb-files/package-tuptime-deb-3.2.01

Please, let me a few days for trying to follow the official way. I see your comment in Debian bug report, wich I opened a few years ago. I want to get tuptime into Debian, but I didn't found any good documentation for python script package. Do you know any well constructed python software for take it as example?

Thanks!

**Comment by anarcat** [comment]
hi!

no problem in waiting as long as you want, of course! :) the rfp has been there for a long time, and there's no sense in putting any pressure here. :)

i didn't notice this was a python script! normally, python packaging in debian is fairly straightforward: the debhelper magic rules notice the `setup.py` file and do "the right thing". however, since you do not have a `setup.py` (or a Makefile) but a custom installer script (which i would recommend converting into a python script), you will need to manually install the file in the debian/install file (but you probably already do that).

looking at the `pkg-files` directory, it looks like you are working on the intermediate output of the package building mechanism: you have the files from the "binary package", not the "source package". normally, you start from a `debian/` directory which has a `rules` files amongst a few others. i often use "dh-make" to prepopulate that directory when creating a new package. then you run "dpkg-buildpackage" or "debuild" to build the package from source directly.

i maintain a few python packages in the debian archive... you may want to look at Monkeysign or Gameclock for examples of fairly well packaged python software:

http://tracker.debian.org/gameclock
https://sources.debian.net/src/gameclock/5.0/
git://git.koumbit.net/gameclock/

Note that gameclock and monkeysign are a little more complicated than tuptime: the code is split in multiple modules which makes the installer more complicated. Maybe you don't need to go through all that trouble and just install `tuptime` directly.

I usually recommend the new maintainers guide:

http://www.debian.org/doc/manuals/maint-guide/index.en.html

.. but now a new guide came up that is supposed to replace the guide, but i haven't reviewed it yet:

http://www.debian.org/doc/manuals/debmake-doc/index.en.html

A shorter, good overview for upstreams like yourself may be this one, if you don't want to get bogged down in the details of writing your own .deb:

http://www.debian.org/doc/manuals/distribute-deb/distribute-deb.html

I would also be happy to recommend more changes to the organisation of your source tree if you find that useful.

Have a nice day!

**Comment by rfrail3** [comment]
Hi Anarcat,


Thanks for your detail response. Reviewing your packages and the docs I feel that I need to dedicate a considerable time for understand the whole thing and skip the easy copy and paste way.

Viewing that you have enought experience, if you want, feel free to take the #638422 bug report. I should not have sent the ITP bug #637180 a few years ago.

Please, if you don't take it, tell me what is the best way to free (close, delete or whatever) the bug report. Maybe an other developer can take it.

I'm open to change anything for improve the contents of this repo. For example, the FreeBSD port that is here was did by a person whith a deeply knowledge of that system.


Thanks for your time.

**Comment by anarcat** [comment]
On 2015-11-23 14:51:18, Ricardo F. wrote:
> Thanks for your detail response. Reviewing your packages and the docs I feel that I need to dedicate a considerable time for understand the whole thing and skip the easy copy and paste way.

Of course, it is a bit of work. However, copy-pasting is fine: there is
a lot of that in building a debian package! :) Also, your code is very
simple, so building a debian package should be very easy.

> Viewing that you have enought experience, if you want, feel free to
> take the #638422 bug report.

I'll see if i can find the time. Unfortunately, it will be more work for
me to package the software *because* the binary files (the `.rpm` and
`.deb` files, specifically) are present. We usually do *not* allow
distributing source-less binary files like this in Debian, and since
Debian also ships with the full source of all the software, we would
have to ship the `.deb` files in the source, which is really strange.

This is why I opened this bug report. :) It would make our lives in
Debian much easier if the binary files were removed from the source
tree. Once that is done, a new release will allow me to ship a clean new
release with a proper source distribution.

> I should not have sent the ITP bug #637180 a few years ago.

That is fine: you were learning the process, and were hoping to package
it! Packaging for Debian can be a little bit difficult, so don't be too
hard on yourself. :)

> Please, if you don't take it, tell me what is the best way to free
> (close, delete or whatever) the bug report. Maybe an other developer
> can take it.

Leaving the bug report open is fine.

> I'm open to change anything for improve the contents of this repo. For
> example, the FreeBSD port that is here was did by a person whith a
> deeply knowledge of that system.

I am also familiar with the FreeBSD port system, and i believe it is not
necessary for you to have a copy of the port in your source tree. It is
already in FreeBSD now (it's how i discovered this software!):

http://svnweb.freebsd.org/ports/head/sysutils/tuptime/

so you do not need a copy of this in git.

This is the same for the RPM: you should ship the RPM as an attachment
to the github release and *not* in the git repository.

I would be happy to make a pull request to accomplish that if you wish,
but it's pretty trivial: just remove the two directories. The important
part is changing your workflow to ship those files in the github
releases from now on!

Thanks for the response!

a.

-- 
Si Dieu est, l'homme est esclave ; 
or l'homme peut, doit être libre, donc Dieu n'existe pas.
Et si Dieu existait, il faudrait s'en débarrasser!
                        - Michel Bakounine

**Comment by rfrail3** [comment]
Hi Anarcat,

Ok, well, don't worry. I will do all changes needed in the repo, starting from removing all .deb and .rpm files. I to want see this proyect into an official repo, now are the first steps... :)

Thanks again for your time and the response.

**Comment by rfrail3** [comment]
Hi Anarcat,

I just delete all the .deb and .rpm files recursively in the history. It is a considerable amount of space:

Before:
    $ du -sh .git/
    5,6M	.git/

Actually:
    $ du -sh .git/
    596K	.git/

What do you need now? Please, tell me what is the next step.

Thanks,

**Comment by anarcat** [comment]
that's awesome, just what i was looking for! i'll close this issue and reopen others when/if there is anything else.

the next step is for me to generate a `debian/` directory with all the goodies. i will probably start from the stuff you already have on the pkg-files branch.

i would also recommend you remove the freebsd port from here, it could be on a separate branch or just removed, as it is in the ports collection.

thanks!
