### ISSUE TITLE
tag and publish a release

### ISSUE THREAD

**Issue by anarcat** [rfrail3/tuptime#12]
so, another thing that is missing here is proper releases. i see zero releases in the [release tab](https://github.com/rfrail3/tuptime/releases), it could be a product of rewriting the history...

i would also recommend using [semantic versionning](http://semver.org) for naming the releases!

looking at the freebsd port makefile, i'll assume the latest code is 3.2.01, but since i am not sure the release is actually associatd with the last commit, i will add a git commit id to the debian version number.

**Comment by rfrail3** [comment]
Yes, before I had some releases. I know that this is not the best way, but I prefer to clean all old references (some with wrong versioning number as the semantic versioning require) and start now as a full stop.

The 3.2.01 was previous OSX compatibility, now is the 3.2.10, but for Debian that its indifferent.

I prefer to wait a few days until this issues are closed for tag a new release with a more mature repo.

Thanks Anarcat,

**Comment by anarcat** [comment]
still - it may be useful to restore the tags to their previous commits if you still can: this can be useful to bisect bugs between different versions if users are running old software. i would understand if you wouldn't want to bother with that work...

no problem for waiting to do a release, let me know if you need help.

**Comment by rfrail3** [comment]
Tags restored, but in the process I overwhelm the merge #17 when you added the Debian files. After some tries to recover it, finally I did a copy of the folder from the last snapshot of the repo who included it.
The FreeBSD port was broken until I did this tag recovering, sorry if that cause problems to somebody.

Anarcat, do you need a new tag or you can use the existing?. In any case I will release a new one when the repo progress a bit more for cover the new changes.

Thanks,

**Comment by anarcat** [comment]
hi.

i do not see a 3.2 tag in the tree right now.

furthermore, it does seem like the pull request was mangled a bit. :) i pushed again a debian branch in my personal repo here: https://github.com/anarcat/tuptime/tree/debian

i can do another pull request if you wish...?

**Comment by rfrail3** [comment]
Yes, please, do it for left in an acceptable state.

After that I will release a 3.2 tag.

Thanks, and sorry for the inconveniences.

2015-11-26 23:08 GMT+01:00 anarcat <notifications@github.com>:

**Comment by anarcat** [comment]
at this point, you should release 3.3, 3.2.2 or higher. the debian package has been published and unless i bump the "epoch" (something we try to avoid in general), 3.2 would be a lower version than what is already in the archive.

i will do a pull request to restore the debian package.

**Comment by anarcat** [comment]
done, in #24.

**Comment by rfrail3** [comment]
Ok, #24 done and relese "3.2.2" available. I don't continue wiht the 'v' before the number present in the other releases.

Thanks Anarcat.

**Comment by anarcat** [comment]
feel free to prepare a native 3.2.2 package. :)

**Comment by rfrail3** [comment]
Ok, I will do it changing the root user as was requested in the issue #13

**Comment by rfrail3** [comment]
Done in issue #13
