### ISSUE TITLE
man page source missing

### ISSUE THREAD

**Issue by anarcat** [rfrail3/tuptime#14]
i noticed that, in the debian package, there is a manpage, and that is great! however, it seems to be missing from the source distribution. i added it back to the debian package, but it would be nice to have the source of the manpage available in the git repo and source distribution.

**Comment by rfrail3** [comment]
I just added the man page to latest/man/tuptime.1 as a source with the version updated. Also, the same file is updated too inside debian directory.

Thanks Anarcat,

**Comment by anarcat** [comment]
you should remove the duplicate from debian/tuptime.1 and change the path to the manpage in debian/tuptime.manpages instead.

i also recommend getting rid of the `latest` directory and move stuff to `src` or simply the toplevel directory. when i first looked at the source, i couldn't find the code because of the unusual directory structure...
