### ISSUE TITLE
It would be nice if the README would state the differences to uptimed and downtimed

### ISSUE THREAD

**Issue by xtaran** [rfrail3/tuptime#18]
It would be nice if the README.md would state the differences (advantages/disadvantages compared) to [uptimed](https://github.com/rpodgorny/uptimed) and [downtimed](http://dist.epipe.com/downtimed/).

**Comment by anarcat** [comment]
i have looked at uptimed a little, and just took a look at downtimed. i agree that documenting the difference would be nice.

here's a list of things i found so far:

* tuptime doesn't run as a daemon. it is only fired through cronjobs running at regular (5 minutes) intervals, and on startup and shutdown. uptimed and downtimed both are daemons always running in the background
* both daemons are written in C while tuptime is written in Python
* downtimed logs into syslog, not sure about the others.
* tuptime writes to a sqlite database, not sure about the others
* last releases:
  * uptimed: 2015-04-07 (0.4.0)
  * downtimed: 2013-07-27 (0.6)
  * tuptime: ? (3.2.10)
* uptimed tracks "uptime records" and sends emails when milestones are reached (e.g. "you have been up for 100 days!)
* both uptimed and downtimed are well distributed in Debian. tuptime only recently entered debian officially.

here's also a openhub comparison: https://www.openhub.net/p/_compare?project_0=uptimed&project_1=downtimed&project_2=tuptime

**Comment by anarcat** [comment]
the openhub comparison has been completed:

it turns out that tuptime is also much smaller than the C counterparts, clocking at 800 LOC vs 2400 for downtimed and 40000 for uptimed. downtimed hasn't seen much activity in the last two years, and uptimed has a similar activity to tuptimed (but is much older).

**Comment by rfrail3** [comment]
xtaran, I hope that the information included in this commit cover your issue. If not, feel free to reopen it.

Thanks for the tips Anarcat,

**Comment by xtaran** [comment]
Thanks! That suffices well.
