### ISSUE TITLE
tuptime should be installed in /usr/sbin/tuptime

### ISSUE THREAD

**Issue by anarcat** [rfrail3/tuptime#23]
I made a change in the way tuptime is installed in the Debian package. I made it be installed in `/usr/sbin` instead of `/usr/bin`. This is because tuptime is expected to be ran as root right now (see #13 for that as well). This follows the FHS standard (see `man hier`) but it breaks the systemd startup script, a bug that was reported in the Debian BTS in https://bugs.debian.org/806380.

Now, there are two ways to fix this:

* patch the debian package to change the systemd unit file
* install the script in `/usr/bin` instead

I would rather patch the systemd unit file, but if #13 is going to be fixed soon, it would make more sense to install the script in `/usr/bin`. Furthermore, it would prefer to avoid diverging from upstream as we wish to handover package management to upstream.

So could we switch to `/usr/bin` all over?

**Comment by rfrail3** [comment]
Ok, #13 is on the way, I'm with you with the idea of install it in /usr/bin, go with it please.

Thanks,

**Comment by anarcat** [comment]
okay then, going with /usr/bin.
