### ISSUE TITLE
should depend on lsb-base

### ISSUE THREAD

**Issue by anarcat** [rfrail3/tuptime#31]
hi!

first off, congratulations: your package will probable be shipped in the next debian release, Debian "stretch" 9. :)

according to the [package tracker](https://tracker.debian.org/pkg/tuptime), there are lintian errors with the debian package. it seems we are [missing a dependency on lsb-base](https://lintian.debian.org/maintainer/rfraile@rfraile.eu.html#tuptime). the details of this issue are [here](https://lintian.debian.org/tags/init.d-script-needs-depends-on-lsb-base.html), basically you just need to add `lsb-base (>= 3.0-6)` to the Depends line.

i mention this as a bug report instead of doing a pull request so we make sure we still have the sponsorship workflow working in here, and that you are familiar with the package tracker.

let me know if you have any questions!

**Comment by rfrail3** [comment]
Hello Anarcat!

Very grateful to hear from you and to see the package in the next Debian relese :)

I just fix the dependency fault and test it with lintian, it didn't report any problem. A new release has been made with this change with the corresponding tag. I think that this is the correct way, you need something more for build and upload it?

Thanks!

**Comment by anarcat** [comment]
that looks great, i'll just build and upload that - thanks!

**Comment by anarcat** [comment]
by the way, if you have any new features or non-release-critical changes you want to include in Debian stretch, you better implement them quick, because the full freeze is on February 5th, after which point only critical bugfixes will be included.
