### ISSUE TITLE
Incorrect time in db

### ISSUE THREAD

**Issue by ovdiyuk** [rfrail3/tuptime#33]
root@raspbx:~/tuptime# tuptime -l
Startup:  1  at  15:48:11 08/05/17
Uptime:   -48 years, 225 days, 11 hours, 12 minutes and 19 seconds
Shutdown: BAD  at  03:00:30 01/01/70
Downtime: 47 years, 139 days, 14 hours, 59 minutes and 5 seconds

Startup:  2  at  17:59:35 08/05/17
Uptime:   -48 years, 225 days, 9 hours, 0 minutes and 56 seconds
Shutdown: BAD  at  03:00:31 01/01/70
Downtime: 47 years, 139 days, 16 hours, 17 minutes and 55 seconds

Startup:  3  at  19:18:26 08/05/17
Uptime:   36 minutes and 59 seconds
Shutdown: BAD  at  19:55:25 08/05/17
Downtime: 4 minutes and 16 seconds

Startup:  4  at  19:59:41 08/05/17
Uptime:   -48 years, 225 days, 7 hours, 0 minutes and 50 seconds
Shutdown: BAD  at  03:00:31 01/01/70
Downtime: 47 years, 139 days, 17 hours, 11 minutes and 39 seconds

Startup:  5  at  20:12:10 08/05/17
Uptime:   -48 years, 225 days, 6 hours, 48 minutes and 19 seconds
Shutdown: BAD  at  03:00:29 01/01/70
Downtime: 47 years, 139 days, 17 hours, 41 minutes and 30 seconds

Startup:  6  at  20:41:59 08/05/17
Uptime:   -48 years, 225 days, 6 hours, 18 minutes and 32 seconds
Shutdown: BAD  at  03:00:31 01/01/70
Downtime: 47 years, 139 days, 19 hours, 22 minutes and 56 seconds

Startup:  7  at  22:23:27 08/05/17
Uptime:   -48 years, 225 days, 4 hours, 37 minutes and 0 seconds
Shutdown: BAD  at  03:00:27 01/01/70
Downtime: 47 years, 139 days, 20 hours, 4 minutes and 45 seconds

Startup:  8  at  23:05:12 08/05/17
Uptime:   -48 years, 225 days, 3 hours, 55 minutes and 16 seconds
Shutdown: BAD  at  03:00:28 01/01/70
Downtime: 47 years, 139 days, 21 hours, 0 minutes and 43 seconds

Startup:  9  at  00:01:11 09/05/17
Uptime:   -48 years, 225 days, 2 hours, 59 minutes and 21 seconds
Shutdown: BAD  at  03:00:32 01/01/70
Downtime: 47 years, 140 days, 5 hours, 55 minutes and 14 seconds

Startup:  10  at  08:55:46 09/05/17
Uptime:   -48 years, 224 days, 18 hours, 4 minutes and 45 seconds
Shutdown: BAD  at  03:00:31 01/01/70
Downtime: 47 years, 140 days, 9 hours, 30 minutes and 12 seconds

Startup:  11  at  12:30:43 09/05/17
Uptime:   -48 years, 224 days, 14 hours, 29 minutes and 48 seconds
Shutdown: BAD  at  03:00:31 01/01/70
Downtime: 47 years, 140 days, 10 hours, 51 minutes and 45 seconds

Startup:  12  at  13:52:16 09/05/17
Uptime:   -48 years, 224 days, 13 hours, 9 minutes and 7 seconds
Shutdown: BAD  at  03:01:23 01/01/70
Downtime: 47 years, 140 days, 11 hours, 47 minutes and 8 seconds

Startup:  13  at  14:48:31 09/05/17
Uptime:   -48 years, 224 days, 12 hours, 12 minutes and 50 seconds
Shutdown: BAD  at  03:01:21 01/01/70
Downtime: 47 years, 140 days, 12 hours, 16 minutes and 6 seconds

Startup:  14  at  15:17:27 09/05/17
Uptime:   -48 years, 224 days, 11 hours, 43 minutes and 52 seconds
Shutdown: BAD  at  03:01:19 01/01/70
Downtime: 47 years, 140 days, 12 hours, 28 minutes and 42 seconds

Startup:  15  at  15:30:01 09/05/17
Uptime:   -48 years, 224 days, 11 hours, 31 minutes and 18 seconds
Shutdown: BAD  at  03:01:19 01/01/70
Downtime: 47 years, 140 days, 12 hours, 38 minutes and 41 seconds

Startup:  16  at  15:40:00 09/05/17
Uptime:   -48 years, 224 days, 11 hours, 21 minutes and 20 seconds
Shutdown: BAD  at  03:01:20 01/01/70
Downtime: 47 years, 140 days, 12 hours, 45 minutes and 33 seconds

Startup:  17  at  15:46:53 09/05/17
Uptime:   -48 years, 224 days, 11 hours, 14 minutes and 26 seconds
Shutdown: BAD  at  03:01:19 01/01/70
Downtime: 47 years, 140 days, 12 hours, 58 minutes and 23 seconds

Startup:  18  at  15:59:42 09/05/17
Uptime:   -48 years, 224 days, 11 hours, 0 minutes and 50 seconds
Shutdown: BAD  at  03:00:32 01/01/70
Downtime: 47 years, 140 days, 13 hours, 31 minutes and 5 seconds

Startup:  19  at  16:31:37 09/05/17
Uptime:   -48 years, 224 days, 10 hours, 28 minutes and 57 seconds
Shutdown: BAD  at  03:00:34 01/01/70
Downtime: 47 years, 140 days, 14 hours, 54 minutes and 41 seconds

Startup:  20  at  17:55:15 09/05/17
Uptime:   -48 years, 224 days, 9 hours, 6 minutes and 5 seconds
Shutdown: BAD  at  03:01:20 01/01/70
Downtime: 47 years, 140 days, 18 hours, 53 minutes and 34 seconds

Startup:  21  at  21:54:54 09/05/17
Uptime:   -48 years, 224 days, 5 hours, 6 minutes and 25 seconds
Shutdown: BAD  at  03:01:19 01/01/70
Downtime: 47 years, 140 days, 19 hours, 0 minutes and 35 seconds

Startup:  22  at  22:01:54 09/05/17
Uptime:   -48 years, 224 days, 4 hours, 59 minutes and 26 seconds
Shutdown: BAD  at  03:01:20 01/01/70
Downtime: 47 years, 140 days, 19 hours, 16 minutes and 24 seconds

Startup:  23  at  22:17:44 09/05/17
Uptime:   -48 years, 224 days, 4 hours, 43 minutes and 36 seconds
Shutdown: BAD  at  03:01:20 01/01/70
Downtime: 47 years, 140 days, 19 hours, 32 minutes and 28 seconds

Startup:  24  at  22:33:48 09/05/17
Uptime:   -48 years, 224 days, 4 hours, 27 minutes and 31 seconds
Shutdown: BAD  at  03:01:19 01/01/70
Downtime: 47 years, 140 days, 20 hours, 11 minutes and 9 seconds

Startup:  25  at  23:12:28 09/05/17
Uptime:   -48 years, 224 days, 3 hours, 48 minutes and 51 seconds
Shutdown: BAD  at  03:01:19 01/01/70
Downtime: 47 years, 140 days, 20 hours, 33 minutes and 53 seconds

Startup:  26  at  23:35:12 09/05/17
Uptime:   -48 years, 224 days, 3 hours, 26 minutes and 7 seconds
Shutdown: BAD  at  03:01:19 01/01/70
Downtime: 47 years, 140 days, 20 hours, 42 minutes and 39 seconds

Startup:  27  at  23:43:58 09/05/17
Uptime:   -48 years, 224 days, 3 hours, 17 minutes and 21 seconds
Shutdown: BAD  at  03:01:19 01/01/70
Downtime: 47 years, 140 days, 20 hours, 57 minutes and 50 seconds

Startup:  28  at  23:59:09 09/05/17
Uptime:   -48 years, 224 days, 3 hours, 2 minutes and 10 seconds
Shutdown: BAD  at  03:01:19 01/01/70
Downtime: 47 years, 140 days, 21 hours, 9 minutes and 50 seconds

Startup:  29  at  00:11:09 10/05/17
Uptime:   -48 years, 224 days, 2 hours, 50 minutes and 10 seconds
Shutdown: BAD  at  03:01:19 01/01/70
Downtime: 47 years, 140 days, 21 hours, 21 minutes and 59 seconds

Startup:  30  at  00:23:18 10/05/17
Uptime:   -48 years, 224 days, 2 hours, 38 minutes and 3 seconds
Shutdown: BAD  at  03:01:21 01/01/70
Downtime: 47 years, 141 days, 5 hours, 49 minutes and 43 seconds

Startup:  31  at  08:51:04 10/05/17
Uptime:   -48 years, 223 days, 18 hours, 10 minutes and 17 seconds
Shutdown: BAD  at  03:01:21 01/01/70
Downtime: 47 years, 141 days, 6 hours, 1 minute and 9 seconds

Startup:  32  at  09:02:30 10/05/17
Uptime:   -48 years, 223 days, 17 hours, 58 minutes and 50 seconds
Shutdown: BAD  at  03:01:20 01/01/70
Downtime: 47 years, 141 days, 6 hours, 30 minutes and 21 seconds

Startup:  33  at  09:31:41 10/05/17
Uptime:   -48 years, 223 days, 17 hours, 29 minutes and 39 seconds
Shutdown: BAD  at  03:01:20 01/01/70
Downtime: 47 years, 141 days, 6 hours, 39 minutes and 37 seconds

Startup:  34  at  09:40:57 10/05/17
Uptime:   -48 years, 223 days, 17 hours, 20 minutes and 26 seconds
Shutdown: BAD  at  03:01:23 01/01/70
Downtime: 47 years, 141 days, 6 hours, 46 minutes and 40 seconds

Startup:  35  at  09:48:03 10/05/17
Uptime:   -48 years, 223 days, 17 hours, 12 minutes and 31 seconds
Shutdown: BAD  at  03:00:34 01/01/70
Downtime: 47 years, 141 days, 7 hours, 12 minutes and 9 seconds

Startup:  36  at  10:12:43 10/05/17
Uptime:   -48 years, 223 days, 16 hours, 48 minutes and 39 seconds
Shutdown: BAD  at  03:01:22 01/01/70
Downtime: 47 years, 141 days, 9 hours, 9 minutes and 59 seconds

Startup:  37  at  12:11:21 10/05/17
Uptime:   -48 years, 223 days, 14 hours, 50 minutes and 0 seconds
Shutdown: BAD  at  03:01:21 01/01/70
Downtime: 47 years, 141 days, 12 hours, 53 minutes and 8 seconds

Startup:  38  at  15:54:29 10/05/17
Uptime:   -48 years, 223 days, 11 hours, 6 minutes and 53 seconds
Shutdown: BAD  at  03:01:22 01/01/70
Downtime: 47 years, 141 days, 15 hours, 0 minutes and 49 seconds

Startup:  39  at  18:02:11 10/05/17
Uptime:   -48 years, 223 days, 8 hours, 59 minutes and 10 seconds
Shutdown: BAD  at  03:01:21 01/01/70
Downtime: 47 years, 141 days, 15 hours, 39 minutes and 41 seconds

Startup:  40  at  18:41:02 10/05/17
Uptime:   -48 years, 223 days, 8 hours, 20 minutes and 18 seconds
Shutdown: BAD  at  03:01:20 01/01/70
Downtime: 47 years, 146 days, 0 hours, 15 minutes and 8 seconds

Startup:  41  at  03:16:28 15/05/17
Uptime:   -48 years, 218 days, 23 hours, 44 minutes and 53 seconds
Shutdown: BAD  at  03:01:21 01/01/70
Downtime: 47 years, 146 days, 17 hours, 17 minutes and 21 seconds

Startup:  42  at  20:18:42 15/05/17
Uptime:   -48 years, 218 days, 6 hours, 42 minutes and 38 seconds
Shutdown: BAD  at  03:01:20 01/01/70
Downtime: 47 years, 146 days, 18 hours, 24 minutes and 22 seconds

Startup:  43  at  21:25:42 15/05/17
Uptime:   -48 years, 218 days, 5 hours, 35 minutes and 55 seconds
Shutdown: BAD  at  03:01:37 01/01/70
Downtime: 47 years, 146 days, 18 hours, 40 minutes and 49 seconds

Startup:  44  at  21:42:26 15/05/17
Uptime:   -48 years, 218 days, 5 hours, 18 minutes and 54 seconds
Shutdown: BAD  at  03:01:20 01/01/70
Downtime: 47 years, 147 days, 15 hours, 22 minutes and 0 seconds

Startup:  45  at  18:23:20 16/05/17
Uptime:   -48 years, 217 days, 8 hours, 38 minutes and 1 second
Shutdown: BAD  at  03:01:21 01/01/70
Downtime: 47 years, 147 days, 15 hours, 28 minutes and 38 seconds

Startup:  46  at  18:29:59 16/05/17
Uptime:   -48 years, 217 days, 8 hours, 31 minutes and 23 seconds
Shutdown: BAD  at  03:01:22 01/01/70
Downtime: 47 years, 147 days, 16 hours, 8 minutes and 3 seconds

Startup:  47  at  19:09:25 16/05/17
Uptime:   -48 years, 217 days, 7 hours, 51 minutes and 58 seconds
Shutdown: BAD  at  03:01:23 01/01/70
Downtime: 47 years, 147 days, 17 hours, 11 minutes and 33 seconds

Startup:  48  at  20:12:56 16/05/17
Uptime:   -48 years, 217 days, 6 hours, 48 minutes and 26 seconds
Shutdown: BAD  at  03:01:22 01/01/70
Downtime: 47 years, 147 days, 17 hours, 43 minutes and 26 seconds

Startup:  49  at  20:44:48 16/05/17
Uptime:   -48 years, 217 days, 6 hours, 16 minutes and 35 seconds
Shutdown: BAD  at  03:01:23 01/01/70
Downtime: 47 years, 147 days, 18 hours, 27 minutes and 39 seconds

Startup:  50  at  21:29:02 16/05/17
Uptime:   -48 years, 217 days, 5 hours, 32 minutes and 20 seconds
Shutdown: BAD  at  03:01:22 01/01/70
Downtime: 47 years, 147 days, 18 hours, 44 minutes and 12 seconds

Startup:  51  at  21:45:34 16/05/17
Uptime:   -48 years, 217 days, 5 hours, 15 minutes and 48 seconds
Shutdown: BAD  at  03:01:22 01/01/70
Downtime: 47 years, 147 days, 19 hours, 6 minutes and 46 seconds

Startup:  52  at  22:08:08 16/05/17
Uptime:   -48 years, 217 days, 4 hours, 52 minutes and 28 seconds
Shutdown: BAD  at  03:00:36 01/01/70
Downtime: 47 years, 147 days, 20 hours, 34 minutes and 14 seconds

Startup:  53  at  23:34:50 16/05/17
Uptime:   -48 years, 217 days, 3 hours, 26 minutes and 2 seconds
Shutdown: BAD  at  03:00:52 01/01/70
Downtime: 47 years, 147 days, 20 hours, 39 minutes and 5 seconds

Startup:  54  at  23:39:57 16/05/17
Uptime:   -48 years, 217 days, 3 hours, 21 minutes and 24 seconds
Shutdown: BAD  at  03:01:21 01/01/70
Downtime: 47 years, 148 days, 20 hours, 41 minutes and 22 seconds

Startup:  55  at  23:42:43 17/05/17
Uptime:   -48 years, 216 days, 3 hours, 18 minutes and 39 seconds
Shutdown: BAD  at  03:01:22 01/01/70
Downtime: 47 years, 148 days, 20 hours, 53 minutes and 2 seconds

Startup:  56  at  23:54:24 17/05/17
Uptime:   -48 years, 216 days, 3 hours, 6 minutes and 56 seconds
Shutdown: BAD  at  03:01:20 01/01/70
Downtime: 47 years, 148 days, 21 hours, 15 minutes and 59 seconds

Startup:  57  at  00:17:19 18/05/17
Uptime:   -48 years, 216 days, 2 hours, 43 minutes and 53 seconds
Shutdown: BAD  at  03:01:12 01/01/70
Downtime: 47 years, 148 days, 21 hours, 37 minutes and 10 seconds

Startup:  58  at  00:38:22 18/05/17
Uptime:   12 minutes and 56 seconds

root@raspbx:~/tuptime# tuptime -V
tuptime version 3.3.1

**Comment by rfrail3** [comment]
I think that you are using a raspberry. That device don't have hardware clock and, at startup, the system date starts from 01/01/70.

Please, read the tuptime-manual.txt in dev branch https://github.com/rfrail3/tuptime/blob/dev/tuptime-manual.txt under the section  "About sync date and time".

Maybe you can fix the problem using time-sync.target or ntp-wait.

**Comment by ovdiyuk** [comment]
Thank you for reply. I got same idea, So I installed RTC couple days ago. It din't solve the issue.
By the way some of the previous version worked correct even without RTC

**Comment by ovdiyuk** [comment]
I see the is no time issue when system starts, the is the issue when reboots.

root@raspbx:~# last -x | grep reboot
reboot   system boot  4.9.26+          Thu Jan  1 03:00 - 15:09 (17304+12:09
reboot   system boot  4.9.26+          Thu Jan  1 03:00 - 15:09 (17304+12:09
reboot   system boot  4.9.26+          Thu Jan  1 03:00 - 15:09 (17304+12:09
reboot   system boot  4.9.26+          Thu Jan  1 03:00 - 15:09 (17304+12:09
reboot   system boot  4.9.26+          Thu Jan  1 03:00 - 23:56 (17303+20:56
...

**Comment by rfrail3** [comment]
I need a raspberry for test and document / fix  this behaviour (maybe I can get one in a couple of weeks).
In the meantime, please, can you paste here the output of "who -b".

Thanks,

**Comment by ovdiyuk** [comment]
root@raspbx:~# who -b
         system boot  1970-01-01 03:00

**Comment by ovdiyuk** [comment]
Hi, 
You was right. It was RTC issue.
Solved by run sudo nano /lib/udev/hwclock-set and comment out these lines:
#if [ -e /run/systemd/system ] ; then
# exit 0
#fi

However, I didn't got how it works earlier w/o RTC....

Thanks a lot for support!
