### ISSUE TITLE
RaspberryPi and reboot and shutdown

### ISSUE THREAD

**Issue by brunosso** [rfrail3/tuptime#34]
Hi i really like this tool!!! 
I fix the issue on Rpi that shows shutdown time in years! Now i want to ask if is possible to fix (or it is normal) the problem of shows every reboot as bad shutdown.

I have an update script run by crontab every 10 days:

> #!/bin/bash -e
> 
> TODAY=$(date +"%d/%m/%Y %T")
> echo ""
> echo "###"
> echo "###   Aggiornamento AVVIATO"
> echo "###"
> echo "###   Ora di inizio: "
> echo "###   "$TODAY""
> echo "###"
> echo ""
> 
> /usr/bin/sudo apt-get update                                                                                                                                                                                       
> 
> echo ""
> 
> /usr/bin/sudo apt-get -y dist-upgrade                                                                                                                                                                              
> 
> echo ""
> 
> #/usr/bin/sudo rpi-update
> /usr/bin/sudo tuptime                                                                                                                                                                                              
> 
> echo ""
> 
> TODAY2=$(date +"%d/%m/%Y %T")
> echo ""
> echo "###"
> echo "###   Aggiornamento COMPLETATO"
> echo "###"
> echo "###   Ora di fine: "
> echo "###   "$TODAY2""
> echo "###"
> echo ""
> 
> /usr/bin/sudo shutdown -r now

i use the calling `/usr/bin/sudo tuptime` because i send via mail the output of entire script to a log file.

**Comment by rfrail3** [comment]
Hi brunosso,

Maybe it's related to the execution of the init script or systemd unit at shutdown.

Please, can you check if that is installed correctly?

Thanks.

**Comment by brunosso** [comment]
what i need to check?

**Comment by rfrail3** [comment]
Perfect, thanks for share the workaround :+1:
