### ISSUE TITLE
Install on Red Hat

### ISSUE THREAD

**Issue by JCN-9000** [rfrail3/tuptime#35]
Hi, I've installed tuptime on a lot of Red Hat 6.x servers, but since I also install `redhat-lsb-core`, which brings the file `/lib/lsb/init-functions`, the installer fails in recognizing the system and tries to use the Debian code to setup the init files ( `update-rc.d tuptime defaults` ) which is obviously not available.
I just swapped the two checks in `tuptime-install.sh` so that Debian comes last and Red Hat is tested before and the install is correct. Or maybe you can check for some other Debian specific file to make the correct choice.
Anyway thanks for this good program.

**Comment by rfrail3** [comment]
Ok, I'll look into this issue, please, let me a few days, now I'm a bit busy, sorry. Thanks.

**Comment by rfrail3** [comment]
Hi, JCN-9000

I just push the fix into dev branch. In a few weeks will be on master, but you can use it anyway.

Thanks for your report,
