### ISSUE TITLE
RPM spec file requires BuildRequires systemd

### ISSUE THREAD

**Issue by frankcrawford** [rfrail3/tuptime#52]
A minor issue I found with the RPM spec file in recent Fedora systems, it requires the addition of:

**BuildRequires: systemd**

to include the definition of %{_unitdir}

(Ref: https://fedoraproject.org/wiki/Packaging:Systemd#Filesystem_locations )

**Comment by rfrail3** [comment]
Hello Frank,

Thanks for the indication to keep the spec file up to date. I just upload the fix to dev branch, it looks nice:
{code}$ rpmlint tuptime.spec
0 packages and 1 specfiles checked; 0 errors, 0 warnings.{code}

Regards,

**Comment by frankcrawford** [comment]
Not a problem.
BTW, another little nit, in the rpm-readme.txt for Fedora you should use "dnf" not "yum".  However, most uses will know what to do anyway.
Regards

**Comment by rfrail3** [comment]
Thanks for the "dnf" tip, I was formed on the old way...
