### ISSUE TITLE
need reboot count using tuptime --tsince -86400 for past 24 hrs

### ISSUE THREAD

**Issue by svshubham01** [rfrail3/tuptime#53]
Hi,
i need the reboot count of the server in the past 24 hrs, found that tuptime --tsince -86400 returns the system info for the past 24 hrs, can anyone help to get the reboot count.
Thanks In Advance

**Comment by rfrail3** [comment]
Hi,

The default output have all the information that you need, from the "System startups" line, you can get the reboots count, which is equal to startups minus one:

`tuptime --tsince -86400 --csv | grep 'System startups' | awk -F\" '{print $4 -1}'`

**Comment by svshubham01** [comment]
Hi,
Thanks for the quick response.

tuptime --tsince -86400 --csv | grep 'System startups' | awk -F\" '{print $4 -1}'

you mean this command returns me the reboot count for the past 24 hours?

**Comment by rfrail3** [comment]
Yes, it is.

**Comment by svshubham01** [comment]
Thanks a lot for your help.. I tested it out and found that it works perfectly for me... :)
