### ISSUE TITLE
Failed to enable unit/tuptime.service -> /dev/null

### ISSUE THREAD

**Issue by Thorben0** [rfrail3/tuptime#57]
Trying to install tuptime on my debian 10 (buster) machine using the install script.
I get this error:
```
++ Tuptime installation script ++

+ Getting source tar file
  [OK]
+ Copying files
  [OK]
+ Creating Tuptime execution user '_tuptime'
useradd: Benutzer »_tuptime« existiert bereits
  [OK]
+ Creating Tuptime db
  [OK]
+ Setting Tuptime db ownership
  [OK]
+ Executing Tuptime with '_tuptime' user for testing
  [OK]
+ Copying Systemd file
Synchronizing state of tuptime.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable tuptime
Failed to enable unit: Unit file /etc/systemd/system/tuptime.service is masked.
```

Same error when trying to enable it manually using systemd
```
systemctl start tuptime.service
Failed to start tuptime.service: Unit tuptime.service is masked
```

```
ls /etc/systemd/system/tuptime.service -hal
lrwxrwxrwx 1 root root 9 Apr 24 21:37 /etc/systemd/system/tuptime.service -> /dev/null
```
Python 3.7

Any help appreciated. Thank you!

**Comment by rfrail3** [comment]
Hello Thorben0,


Systemd gives you the clue, the tuptime service is masked, so it isn't possible to enable the unit when the script tries to do it.

At some point before, in your system, someone link the `tuptime.service` file to `/dev/null`, probably by executing `systemctl mask tuptime` like here:

```
# systemctl mask tuptime
Created symlink /etc/systemd/system/tuptime.service → /dev/null.
```

Since that moment, the file unit is the symlink that you have:

```
# ls /etc/systemd/system/tuptime.service -hal
lrwxrwxrwx 1 root root 9 Apr 25 15:44 /etc/systemd/system/tuptime.service -> /dev/null
```
But the solution is easy, unlik it:

```
# unlink /etc/systemd/system/tuptime.service
```
And execute again the installation script:
```
# bash <(curl -Ls https://git.io/tuptime-install.sh)

++ Tuptime installation script ++

+ Getting source tar file
  [OK]
+ Copying files
  [OK]
+ Creating Tuptime execution user '_tuptime'
useradd: user '_tuptime' already exists
  [OK]
+ Creating Tuptime db
  [OK]
+ Setting Tuptime db ownership
  [OK]
+ Executing Tuptime with '_tuptime' user for testing
  [OK]
+ Copying Systemd file
  [OK]
+ Copying Cron file
  [OK]
+ Enjoy!
```

Note, as you're using Debian, Tuptime can be installed from the repos with `apt install tuptime` (but the version is a bit older nowadays).

**Comment by Thorben0** [comment]
It's working grat now, thank you!
I wonder what created the symlink to '/dev/null' in the first place 🤔

Also, shouldn't thee script add some cronjob? It says somewhre in the README to be bundled with. Can't find any in 'crontab -e'

**Comment by rfrail3** [comment]
Yes, it uses cron for the scheduled run (but it can use systemd timers too, but it isn't common).

Not all cron task are listed under 'crontab -e', only your user current ones.

You need to look into "/etc/cron.d/tuptime", the installation adds this file for that purpose.
