### ISSUE TITLE
tuptime-plot1.py got IndexError

### ISSUE THREAD

**Issue by roachsinai** [rfrail3/tuptime#60]
Hi @rfrail3 first try tuptime-plot1.py on a new computer got below error:

```
$ python tuptime-plot1.py -f ~/tuptime/tuptime.db
Default end:    now
Default begin:  since 7 days ago
Begin datetime: 22-Nov-2021 00:00:00
End datetime:   29-Nov-2021 23:59:59
Ranges on list: 8
0 range --->    0 events
1 range --->    0 events
2 range --->    0 events
3 range --->    0 events
4 range --->    0 events
5 range --->    0 events
6 range --->    1 events
7 range --->    0 events
Ranges got:     8
Traceback (most recent call last):
  File "tuptime-plot1.py", line 291, in <module>
    main()
  File "tuptime-plot1.py", line 231, in main
    days['up'].append(i[0])
IndexError: list index out of range
```

and tuptime.db is in below zip file:

[tuptime.zip](https://github.com/rfrail3/tuptime/files/7615034/tuptime.zip)

**Comment by roachsinai** [comment]
> tuptime-plot1.py -f ~/tuptime/tuptime.db

Python version is 3.7.4.

And lastest version of AUR tuptime, run the script in lastest tuptime (download by git clone).

**Comment by rfrail3** [comment]
AUR still have an old Tuptime version 4.1.0. I just reproduce the issue on a testing enviroment. 

Please, update to the latest Tuptime version, 5.0.2

You could replace the /src/bin/tuptime file with the one from this repo https://raw.githubusercontent.com/rfrail3/tuptime/master/src/tuptime

**Comment by roachsinai** [comment]
@rfrail3 yes update Tuptime, and regenerate tuptime.db fix this issue.

But just wonder why the db file in the zip file which I uploaded works well the first time you plot it?

**Comment by rfrail3** [comment]
Great to know that.

I tested it with the 5.x release, that's why it worked.

**Comment by roachsinai** [comment]
> I tested it with the 5.x release, that's why it worked.

One more try. I generated db use version 4.x, test plot use version 5.x failed (but seems this situation worked for you as the uploaded db file is version 4.x).

The worked situation for me is regenerate version 5.x db and plot use 5.x code.
