### ISSUE TITLE
Replace sys.exit(-1) by sys.exit(1)

### ISSUE THREAD

**Issue by lcheylus** [rfrail3/tuptime#67]
In `tuptime` Python code, `sys.exit(-1)` is used for error code. Generally, we use 1 for error code in this case => `sys.exit(1)`.

**Comment by rfrail3** [comment]
Appreciate that you look into this, it's fixed on dev branch.

**Comment by lcheylus** [comment]
After review of your last commits in `master` branch, it's OK : every `sys.exit` uses 1 for error code.
