### ISSUE TITLE
How to Reset Tuptime?

### ISSUE THREAD

**Issue by P4n1kH0u53** [rfrail3/tuptime#8]
My team is creating a distribution that will include the tuptime package. We found that when we install our distribution image, tuptime reports the amount of time that our distribution image has been live (we occasionally install the image and modify it while it is running, then recreate it).

I want our images to start with tuptime at 0 each time they get installed.  What is the correct way to reset tuptime back to 0?

**Comment by rfrail3** [comment]
Hi P4n1kH0u53,

Simply delete the database file "/var/lib/tuptime/tuptime.db". Tuptime will create it if it doesn't exist in the first execution.

Thanks,
